# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-02 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formpatterns', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormFields',
            new_name='FormField',
        ),
        migrations.RenameField(
            model_name='formfield',
            old_name='field_types',
            new_name='field_type',
        ),
    ]
