# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-02 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formpatterns', '0002_auto_20171102_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'text'), ('email', 'email'), ('phone', 'phone')], default='text', max_length=25),
        ),
    ]
