# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-02 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('formpatterns', '0003_auto_20171102_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='phone', max_length=128, verbose_name='phone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'text'), ('email', 'email'), (phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='phone'), 'phone')], default='text', max_length=25),
        ),
    ]
