# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-02 18:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('formpatterns', '0004_auto_20171102_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'text'), (django.core.validators.EmailValidator(), 'email'), (phonenumber_field.modelfields.PhoneNumberField(max_length=128), 'phone')], default='text', max_length=25),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
    ]
