# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-02 21:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('formpatterns', '0005_auto_20171102_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'text'), (django.core.validators.EmailValidator(), 'example@email.mail'), (phonenumber_field.modelfields.PhoneNumberField(max_length=128), '+9123456789'), (django.db.models.fields.DateTimeField, '2017-01-01')], default='text', max_length=25),
        ),
    ]
